config/routes.rb
BattlePuzzles::Application.routes.draw do

  devise_for :users

  resources :users
  resources :armies
  resources :divisions
  
  get 'army/update_nations', :as => 'update_nations', :to => 'armies#update_nations'
  
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

end

app/models/army.rb
class Army < ActiveRecord::Base
  attr_accessible :name, :era_id, :nation_id, :divisions_allowed, :battalions_allowed, :total_xp, :user_id, :divisions_attributes

  belongs_to :user
  belongs_to :era
  belongs_to :nation
  has_many :divisions, :dependent => :destroy
  
  validates :name, presence: true, length: { maximum: 50 }
  default_scope order('updated_at DESC')

  accepts_nested_attributes_for :divisions, :reject_if => lambda { |a| a[:name].blank? } , :allow_destroy => true
end

app/models/battalion.rb
class Battalion < ActiveRecord::Base
  attr_accessible :health, :name, :division_id, :unit_class_id

  belongs_to :division
  belongs_to :unit_class
end

app/models/division.rb
class Division < ActiveRecord::Base
  attr_accessible :name, :battalions_attributes
  
  belongs_to :army
  has_many :battalions, :dependent => :destroy

  accepts_nested_attributes_for :battalions, :reject_if => lambda { |a| a[:name].blank? } , :allow_destroy => true
end

app/models/era.rb
class Era < ActiveRecord::Base
  attr_accessible :name
end

app/models/nation.rb
class Nation < ActiveRecord::Base
  belongs_to :era
  attr_accessible :name, :era_id, :flag_img
  
  def self.of_era(per)
    if per
      where('era_id == ?', per.to_i)
    else
      scoped
    end
  end
end

app/models/unit_class.rb
class UnitClass < ActiveRecord::Base
  attr_accessible :internal_name, :move_pts, :name, :spec_pts, :strike_pts

  def self.selectable
    where('id < 8')
  end
end

app/models/unit_type.rb
class UnitType < ActiveRecord::Base

  belongs_to :nation
  belongs_to :unit_class
  attr_accessible :img_name, :name, :nation_id, :unit_class_id

  def self.of_nat(natid)
    if natid
      where('nation_id == ?', natid.to_i)
    else
      scoped
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :gamer_name, :games_allowed, :password, :password_confirmation, :remember_me, :role
  
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :gamer_name, presence: true, uniqueness: true, length: { maximum: 40 }
  validates :role, :inclusion => { :in => %w(admin player), :message => "must be admin or player" }
  
  has_many :armies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def set_current_user
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end
  end
	
end

app/controllers/armies_controller.rb
class ArmiesController < ApplicationController
  before_filter :find_army, except: [:index, :new, :create, :update_nations]
  before_filter :set_current_user
  respond_to :html, :js
  
  def index
    @armies = @user.armies
  end

  def show
    # @army = @user.armies.find params[:id]
    @type_names_array = UnitType.where('nation_id == ?', @army.nation_id).pluck(:name)
    @type_pics_array = UnitType.where('nation_id == ?', @army.nation_id).pluck(:img_name)
  end

  def new
    @eras = Era.all.map{|p| [p.name, p.id]}.insert(0, "Select an Era to Play")
    @nations = []
    @army = @user.armies.new

    (@army.divisions_allowed).times do
      division = @army.divisions.build
      (@army.battalions_allowed).times { division.battalions.build }
    end
  end

  def create
    @army = @user.armies.new(params[:army])
    if @army.save
      redirect_to @army
    else
      render :edit
    end 
  end

  def edit
    # @army = Army.find params[:id]
    if @army.divisions.count == 0 
      division = @army.divisions.build
      (@army.battalions_allowed).times { division.battalions.build }
    end
    @type_names_array = UnitType.where('nation_id == ?', @army.nation_id).pluck(:name)
  end

  def update
    if @army.update_attributes(params[:army])
      redirect_to @army
    else
      render :edit
    end
  end

  def destroy
    if @army.destroy
      @armies = @user.armies
      respond_to do |format|
        format.js {}
      end
    else
      redirect_to @army, error: "Error deleting Army. Try again or contact game administrator"
    end
  end
  
  def find_army
    @army = Army.find(params[:id])
  end

  def update_nations
    # map to name and id for use in our options_for_select
    puts "you got to the update_nationalities method"
    @nations = Nation.of_era(params[:era_id]).map{|n| [n.name, n.id]}.insert(0, "Select a Nation to Play")
  end

end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_filter :find_division, except: [:index, :new, :create]
  before_filter :set_current_user
  respond_to :html, :js
	
  def index
		@divisions = @army.divisions
  end

  def show
    @type_names_array = UnitType.where('nation_id == ?', @division.army.nation_id).pluck(:name)
    @type_pics_array = UnitType.where('nation_id == ?', @division.army.nation_id).pluck(:img_name)		
  end

  def new
    @division = @army.divisions.new
    (@army.battalions_allowed).times { division.battalions.build }
	end
	
  def create
	  @division = @army.divisions.new(params[:division])
    if @division.save
      redirect_to @division
    else
      render :edit
    end 
  end

  def edit
    if @division.battalions.count == 0 
      (@division.army.battalions_allowed).times { @division.battalions.build }
    end
    @type_names_array = UnitType.where('nation_id == ?', @division.army.nation_id).pluck(:name)
	end

  def update
    if @division.update_attributes(params[:division])
      redirect_to @division
    else
      render :edit
    end	
  end

  def destroy
    if @division.destroy
      @divisions = @army.divisions
      respond_to do |format|
        format.js {}
      end
    else
      redirect_to @division, error: "Error deleting Division. Try again or contact game administrator"
    end	
  end
	
	def find_division
    @division = Division.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorization_check
  def index
    @eras = Era.all
    @nations = Nation.all
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # load_and_authorize_resource
	# helper_method :sort_column, :sort_direction
  
  def index
		@users = User.all
  end

  def show
			@user = User.find(params[:id])
  end
	
	def new
		@user = User.new
  end

  def create
		@user = User.new(params[:user])
		if @user.save
			redirect_to @user
		else
			render :edit
		end
  end

  def edit
		@user = User.find(params[:id])	
  end

  def update
  	@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			redirect_to @user
		else
			render :edit
		end
  end

  def destroy
  	@user = User.find(params[:id])
		if @user.destroy
			redirect_to users_path
		else
			flash[:error] = "Error deleting user. Try again or contact sysadmin"
			redirect_to @user
		end
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_remove_fields(name, f, options = {})
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)", options)
  end
    
  def link_to_add_fields(name, f, association, options = {})
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")", options)
  end

end

app/helpers/armies_helper.rb
module ArmiesHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/armies/_armies.html.erb
<% @armies.each do |army| %>
	<div class="well" id="armywell">
    
    
		<h2><%= army.name %></h2>
		<table class="table">
			<tr>
				<td>xp: <strong><%= army.total_xp %></strong></td>
				<td>era: <strong><%= army.era.name %></strong></td>
				<td>playing as: <strong><%= army.nation.name %></strong></td>
				<td><a data-toggle="collapse" data-parent="#armywell" href="#collapse-<%= army.id %>"><i class="icon-eye-open"/></a></td>
				<td><%= link_to('<i class="icon-edit"/>'.html_safe, edit_army_path(army), title: "Edit #{army.name}") %></td>
				<td><%= link_to('<i class="icon-remove"/>'.html_safe, army, method: :delete, remote: true, confirm: "Are you sure?", title: "Delete #{army.name}") %></td>
			</tr>
		</table>
		

    <div id="collapse-<%= army.id %>" class="collapse in">
			<p>&nbsp;</p>
			<% if army.divisions.count == 0 %>
				<%= link_to "Click here to add divisions", edit_army_path(army) %>
			<% else %>
				<table class="table table-striped">
					<tr>
						<th>Name</th>
						<th>Units</th>
						<th colspan="3">Commands</th>
					</tr>
					<% army.divisions.each do |division| %>
						<tr class="fields">
							<td><%= division.name %></td>
							<td>
								<% division.battalions.each do |bn| %>
									<%= image_tag("/assets/icon-#{bn.unit_class_id}.png") %>
								<% end %>
							</td>
							<td><%= link_to('<i class="icon-eye-open"/>'.html_safe, division, title: "Show #{division.name}") %></td>
							<td><%= link_to('<i class="icon-edit"/>'.html_safe, edit_division_path(division), title: "Edit #{division.name}") %></td>
							<td><%= link_to('<i class="icon-remove"/>'.html_safe, division, method: :delete, remote: true, confirm: "Are you sure?", :title => "Delete #{ division.name }.") %></td>
						</tr>
					<% end %>
				</table>
			<% end %>
    </div>
  </div>
<% end %>

app/views/armies/_division_fields.html.erb

<div class="fields">
  <div class="well">
    <a data-target="#myModal" role="button" class="btn pull-right" data-toggle="modal"><i class="icon-th-list"></i></a>
    <fieldset>
      <legend>Division: <%= "#{f.object.name}" unless f.object.name.nil? %> </legend>
      <p >
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: 'New-Div-Name', input_html: { class: "span2" } %>
        <%= link_to_remove_fields "remove", f, { class: 'btn btn-mini btn-warning' } %>
      </p>
    </fieldset>

  </div>
</div>

app/views/armies/_form.html.erb
<%= simple_form_for @army, html: { class: 'form-horizontal' } do |f| %>

  <fieldset>
    <legend><%= "#{ @army.name } " unless @army.name.nil?  %>Army Information</legend>
    <%= f.error_notification %>

    <%= f.input :name, input_html: { class: "span5" } %>
    <% if @army.new_record? %>
      <%= f.association :era, label_method: :name, value_method: :id, input_html: { class: "span5", 'data-url' => update_nations_path } %>
      <%= f.input :nation_id, as: :select, collection: @nations, input_html: { class: "span5" } %>
    <% else %>
      <div class="row">
        <div class="span2"></div>
        <div class="alert alert-info span6">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Note:</h4>
          <p>Era and Nation settings are not editable for existing armies. Start a new Army to play Battle Puzzles in a different era or with a different nation.</p>
        </div>
        <div class="span2"></div>
      </div>
    <% end %>

  </fieldset>


  <fieldset>
    <% if @army.name.blank? %>
      <legend>Divisions <%= "that are in your new army" %></legend>
    <% else %>
      <legend>Units in your army <%= " (#{f.object.divisions_allowed} allowed with #{f.object.battalions_allowed} battalions each)" %></legend>
    <% end %>

    <%= f.fields_for :divisions do |builder| %>
      <%= render('division_fields', :f => builder) %><br />
    <% end %>

    <p>
      <%= link_to_add_fields("Add a Division", f, :divisions, class: "btn btn-primary", :title => "Add a new Division to the Army.") %>
    </p>
  </fieldset>

  <div class='modal-footer'>
    <%= f.button :submit, 'Save', { class: "btn btn-success", title: "Save the changes to this Army." } %>
    <%= link_to("Cancel", armies_path, :confirm => "Are you sure you want to cancel?  Any changes will be lost.", :class => "btn btn-inverse", :title => "Cancel the changes and return to the Home page.") %>
  </div>

<% end %>

app/views/armies/_unitpane.html.erb
<div class="unitpane">
  <table class="table table-striped">
    <tr>
      <th>Sample</th>
      <th>Description</th>
    </tr>
    <tr>
      <td><%= image_tag("/assets/gbww2_inf1.png", size: "64x43", class: "media-object") %></td>
      <td>
        <h5 class="media-heading">Defensive Infantry</h5>
        <p>Moves 1 hex; Fires down alternate spines;Strikes infantry for 3 points.</p>
      </td>
    </tr>
    <tr>
      <td><%= image_tag("/assets/sovww2_inf2.png", size: "64x43", class: "media-object") %></td>
      <td>
        <h5 class="media-heading">Assault Infantry</h5>
        <p>Moves 3 hexes; Grabs infantry or artillery; Strikes for 3 points.</p>
      </td>
    </tr>
    <tr>
      <td><%= image_tag("/assets/gerww2_arty1.png", size: "64x43", class: "media-object") %></td>
      <td>
        <h5 class="media-heading">Light Artillery</h5>
        <p>Moves 1 hex; Fires down alternate spines;Strikes any hex for 4 points.</p>
      </td>
    </tr>
    <tr>
      <td><%= image_tag("/assets/usww2_arty2.png", size: "64x43", class: "media-object") %></td>
      <td>
        <h5 class="media-heading">Heavy Artillery</h5>
        <p>Cannot move; Strikes any hex for 7 points.</p>
      </td>
    </tr>
    <tr>
      <td><%= image_tag("/assets/gerww2_mob1.png", size: "64x43", class: "media-object") %></td>
      <td>
        <h5 class="media-heading">Anti-Cavalry/Tank</h5>
        <p>Moves 1 hex; Fires down alternate spines;Strikes cav/tanks for 4 points.</p>
      </td>
    </tr>
    <tr>
      <td><%= image_tag("/assets/sovww2_mob2.png", size: "64x43", class: "media-object") %></td>
      <td>
        <h5 class="media-heading">Assault Cavalry/Tank</h5>
        <p>Moves 7 hexes; Overruns infantry or artillery; Strikes for 3 points.</p>
      </td>
    </tr>
    <tr>
      <td><%= image_tag("/assets/gbww2_scout.png", size: "64x43", class: "media-object") %></td>
      <td>
        <h5 class="media-heading">Scouts (Recce)</h5>
        <p>Does not need to move; Reveals all enemy units.</p>
      </td>
    </tr>
  </table>
</div>

app/views/armies/destroy.js.erb
$('#armylist').html("<%= escape_javascript( render('armies') ) %>");

app/views/armies/edit.html.erb
<div id="army_fields">
  <h1>Edit <%= @army.name %></h1>
    <%= render('form')%>
</div>

<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Unit Classes</h3>
  </div>
  <div class="modal-body">
    <%= render 'unitpane' %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/armies/index.html.erb
<h1>My Armies</h1>

<!-- temp table to test functions -->
<div id="armylist">
  <%= render 'armies' %>

</div>
<p><%= link_to 'Create New Army', new_army_path, { class: "btn btn-success" } %></p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<!-- end table -->

app/views/armies/new.html.erb
<h1>Create a New Army</h1>

<div id="army_fields"><%= render('form')%></div>

app/views/armies/show.html.erb
<h1>Show: <%= @army.name %>  <%= link_to 'Edit', edit_army_path(@army), { :class => "btn btn-mini btn-warning" } %></h1>
<% @army.divisions.each do |dv| %>
    <h3><%= dv.name %></h3>
		<% if dv.battalions.count > 0 %>
			<ul class="thumbnails">
				<% dv.battalions.each do |bn| %>
						<li class="span3">
							<div class="thumbnail">
								<h6><%= bn.unit_class.name unless bn.unit_class.nil? %></h6>
								<%= bn.name %><br />
								<% if bn.unit_class.nil?  %>
									<%= image_tag("/assets/blankunit.png") %>
							<% else %>
									<%= image_tag("#{@type_pics_array[bn.unit_class_id - 1]}") %>
							<% end %>
								<%= @type_names_array[bn.unit_class_id - 1] %>
							</div>
						</li>
				<% end %>
			</ul>
		<% else %>
			<p><%= link_to "Click here to add battalions", edit_division_path(dv) %></p>
		<% end %>
<% end %>

<p><span style="font: italic 10px;">Last played: <%= @army.updated_at.strftime("%m/%d/%Y") %></span></p>
<p></p>

app/views/armies/update_nations.js.erb
$('#army_nation_id').html("<%= escape_javascript(options_for_select(@nations)) %>");

app/views/divisions/_battalions_table.html.erb

<table id="battalions-table" class="table table-striped">
  <thead>
  <th>Battalions</th>
  <th>Unit Class</th>
  <th>Description</th>
  <th></th>
  </thead>

  <tbody>
  <%= f.fields_for(:battalions) do |bn_form| %>
    <tr class="fields">
      <td><%= bn_form.text_field(:name, class: 'span3') %></td>
      <td><%= bn_form.collection_select(:unit_class_id, UnitClass.selectable, :id, :name) %></td>
      <td>
				<% if bn_form.object.unit_class_id.nil? %>
					<em>unassigned</em>
				<% else %>
					<%= image_tag("/assets/icon-#{bn_form.object.unit_class_id}.png") %>
					<%= @type_names_array[bn_form.object.unit_class_id - 1] %>
				<% end %>
			</td>
      <%# if current_page?(new_division_path) || current_page?(edit_division_path) %>
      <td>
        <%= link_to_remove_fields('<i class="icon-remove"></i>'.html_safe, bn_form, :title => "Delete this Battalion") %>
      </td>
      <%# end %>
    </tr>
  <% end %>

  </tbody>
</table>


app/views/divisions/destroy.js.erb
$('#bn-list').html("<%= escape_javascript( render('battalions_table') ) %>");

app/views/divisions/edit.html.erb
<%= simple_form_for @division, html: { class: 'form-horizontal' } do |f| %>

	<fieldset>
		<legend>Division: <%= "#{f.object.name}" unless f.object.name.nil? %> </legend>
		<p>
			<%= f.label :name %>
			<%= f.text_field :name, placeholder: 'New-Div-Name', input_html: { class: "span2" } %>
		</p>
  </fieldset>
	
  <fieldset>
    <% if @division.name.blank? %>
      <legend>Battalions in your division</legend>
    <% else %>
      <legend>Units in your division <%= " (#{f.object.army.battalions_allowed} battalions allowed)" %></legend>
    <% end %>

    <div id="bn-list"><%= render('battalions_table', :f => f) %></div>

    <p>
      <%= link_to_add_fields("Add a Battalion", f, :battalions, class: "btn btn-mini btn-primary", :title => "Add a new Battalion to the Division") %>
    </p>
  </fieldset>

  <div class='modal-footer'>
    <%= f.button :submit, 'Save', { class: "btn btn-success", title: "Save the changes to this Division." } %>
    <%= link_to("Cancel", divisions_path, :confirm => "Are you sure you want to cancel?  Any changes will be lost.", :class => "btn btn-inverse", :title => "Cancel the changes and return to the Home page") %>
  </div>

<% end %>

app/views/divisions/new.html.erb
<h1>Divisions#new</h1>
<p>Find me in app/views/divisions/new.html.erb</p>

app/views/divisions/show.html.erb
<h1>Divisions#show</h1>
<h3>Show: <%= @division.name %>  <%= link_to 'Edit', edit_division_path(@division), { :class => "btn btn-mini btn-warning" } %></h3>

	<ul class="thumbnails">
		<% @division.battalions.each do |bn| %>
				<li class="span3">
					<div class="thumbnail unit">
						<h6><%= bn.unit_class.name unless bn.unit_class.nil? %></h6>
						<%= bn.name %><br />
						<% if bn.unit_class.nil?  %>
							<%= image_tag("/assets/blankunit.png") %>
					<% else %>
							<%= image_tag("#{@type_pics_array[bn.unit_class_id - 1]}") %>
					<% end %>
						<%= @type_names_array[bn.unit_class_id - 1] %>
					</div>
				</li>
		<% end %>
	</ul>

app/views/home/index.html.erb
<div class="hero-unit">
	<h1>Welcome! (Home#index)</h1>
	<p>Puzzle Warfare is the easy to learn, hard to master game of historical conquest played out through puzzles. You must be logged in, in order to play the game.</p>
	<p>
		<% if !user_signed_in? %>
			<%= link_to "Sign in", new_user_session_path, { class: "btn btn-primary btn-large" } %>
		<% else %>
			<h3 class="notice"><%= notice %></h3>
			<p>You have <%= current_user.armies.count %> armies.</p>
			<%= link_to "View My Armies", armies_path, { class: "btn btn-primary btn-large" } %>
		<% end %>
  </p>
</div>

<div class="span12">
	<legend>Play an existing campaign:</legend>
	<ul class="thumbnails">
	<% if user_signed_in? %>
		<% current_user.armies.each do |army| %>
			<li class="span4">
				<div class="thumbnail">
					<img src="http://placehold.it/320x200" alt="ALT NAME">
					<div class="caption">
						<h3><%= army.name %></h3>
						<p>Nation: <%= army.nation.name %></p>
						<p>XP: <%= army.total_xp %></p>
						<p>Campaign progress:</p>
						<div class="progress">
							<div class="bar" style="width: 60%;"></div>
						</div>
						<p align="center">
							<%= link_to "Go!", army, { class: "btn btn-primary btn-block" } %>
						</p>
					</div>
				</div>
			</li>
		<% end %>
	<% end %>
		
		<li class="span4">
			<div class="thumbnail">
				<img src="http://placehold.it/320x200" alt="WW2">
				<div class="caption">
					<h3>World War II <small>(1939-45)</small></h3>
					<p>Engage in desperate battles of breakthrough, exploitation and pursuit as you guide your nation to victory. Units include infantry, engineers, artillery, and tanks. Special powers include railroad guns, dreaded heavy tanks, and even carpet bombing!</p>
					<p align="center"><a href="#" class="btn btn-primary btn-block">New Game</a></p>
				</div>
			</div>
		</li>
		<li class="span4">
			<div class="thumbnail">
				<img src="http://placehold.it/320x200" alt="Napoleonics">
				<div class="caption">
					<h3>Napoleonic Wars <small>(1800-15)</small></h3>
					<p>Will you conquer Europe, or turn back the Gallic Hordes?  Units include infantry (in line, column and square), field and siege artillery, light and heavy cavalry. Special powers include bayonnet charges, cannister fire, and forcing your opponent to surrender!</p>
					<p align="center"><a href="#" class="btn btn-primary btn-block">New Game</a></p>
				</div>
			</div>
		</li>
		<li class="span4">
			<div class="thumbnail">
				<img src="http://placehold.it/320x200" alt="Billy Yank vs Johnny Reb">
				<div class="caption">
					<h3>US Civil War <small>(1861-65)</small></h3>
					<p>Will you fight to preserve the Union, or to raise the Stars &amp; Bars? Units include infantry (in line, column and in breastworks), field artillery, and cavalry. Special powers include repeating rifles, cannister fire, gatling guns, and the Rebel Yell!</p>
					<p align="center"><a href="#" class="btn btn-primary btn-block">New Game</a></p>
				</div>
			</div>
		</li>

	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BattlePuzzles</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="head">
		<div class="row-fluid">
			<div class="span12">
				<div class="span6">
					<div class="media">
						<img src="/assets/bp_logo.png" class="pull-left media-object"> 
						<h1 style="color: #616d55;">BattlePuzzles</h1>
						<p class="muted">easy to learn | lifetime to master</p>
					</div>
				</div>
				<div class="span4 offset2" style="margin-top:15px;">
					<p class="text-right muted">
						<% if user_signed_in? %>
							<small>Signed in as <%= current_user.email %></small> <br />
							<%= link_to "Sign out", destroy_user_session_path, { class: "btn" }, :method => :delete %>
						<% else %>
							<%= link_to "sign in", new_user_session_path, { class: "btn" } %> or <%= link_to "register", new_user_registration_path, { class: "btn" } %>
						<% end %>
					</p>
				</div>
			</div>
		</div>
		<div class="navbar">
			<div class="navbar-inner">
				<div class="container">
					<ul class="nav">
						<li><%= link_to 'Home', root_url %></li>
						<li><%= link_to 'Manage Armies', armies_path %></li>
						<li><%= link_to 'New Army', new_army_path %></li>
						<li><%= link_to 'Users (admin only)', users_path %></li>
					</ul>                      
				</div>
			</div>
		</div>
	</div>	

	
	<div class='container'>

		<%= yield %>
	</div>

	
	<div class='container'>
		<div class='footer'>
			<div class="row-fluid">
				<div class="span12">
					<div class="span2" style="width: 15%;">
						<ul class="unstyled">
							<li><li>
						</ul>
					</div>
					<div class="span2" style="width: 15%;">
						<ul class="unstyled">
							<li>Games<li>
							<li><a href="#">BattlePuzzles</a></li>
							<li><a href="#">QuestPuzzles</a></li>
							<li><a href="#">NavalPuzzles</a></li>
							<li><a href="#">Mobile apps</a></li>							
						</ul>
					</div>
					<div class="span2" style="width: 15%;">
						<ul class="unstyled">
							<li>Support<li>
							<li><a href="#">Forums</a></li>
							<li><a href="#">Billing issues</a></li>
							<li><a href="#">Site status</a></li>
						</ul>
					</div>
					<div class="span2" style="width: 15%;">
						<ul class="unstyled">
							<li>Company<li>
							<li><a href="#">About us</a></li>
							<li><a href="#">Blog</a></li>
							<li><a href="#">Contact</a></li>
						</ul>
					</div>
					<div class="span2" style="width: 15%;">
						<ul class="unstyled">
							<li>Legal<li>
							<li><a href="#">Terms of Service</a></li>
							<li><a href="#">Privacy</a></li>
							<li><a href="#">Security</a></li>
							<li>reserved</li>							
						</ul>
					</div>
				</div>
			</div>
			<div class="row-fluid footer2">
				<div class="span12">
					<div class="span8">
						<p class="muted pull-left">
						Army Index and Footer design courtesy of <a href="#">Bootsnipp.com.</a>    
						</p>
					</div>
					<div class="span4">
						<p class="muted pull-right">&copy; 2013, Kevin Browne. All rights reserved</p>
					</div>
				</div>
			</div>
		</div>
	</div>

</body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>find me in app/views/users</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>find me in app/views/users</p>